apiVersion: apps/v1

kind: Deployment

metadata:
  name: basic-deployment

spec: # spec do deployment
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec: # spec do pod
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 100Mi
              cpu: 0.2 # ou 200m
            limits:
              cpu: 0.25 # ou 250m
              # ao contrário da CPU, se o pod atingir o limite de memória, ele será reiniciado pelo Kubernetes
              memory: 200Mi
          volumeMounts: # monta o volume efetivamente
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: true

      volumes: # definição de volumes
        - name: nginx-conf
          configMap:
            name: basic-configmap
            items:
              - key: nginx.conf
                path: nginx.conf
