apiVersion: autoscaling/v1

kind: HorizontalPodAutoscaler

metadata:
  name: nginx-hpa

spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: basic-deployment
  targetCPUUtilizationPercentage: 20 # O escalonamento irá iniciar quando a CPU atingir 20%